function params = getConfig(deviceType, varargin)
    % デバイス設定とプリセットを読み込むための関数
    %
    % 入力:
    %   deviceType - デバイスタイプ ('epocx', 'mn8', 'openbci8', 'openbci16')
    %   varargin   - 名前-値ペアのパラメータ
    %     'preset' - プリセット名 (例: 'template', 'character')
    %
    % 出力:
    %   params    - 設定パラメータを含む構造体

    % 入力パーサーの設定
    p = inputParser;
    p.addRequired('deviceType', @(x) ischar(x) || isstring(x));
    p.addParameter('preset', '', @(x) ischar(x) || isstring(x));

    % パース実行
    parse(p, deviceType, varargin{:});

    try
        % デバッグ出力
        fprintf('=== 設定読み込み ===\n');
        
        % プリセット名の決定
        if isempty(p.Results.preset)
            presetName = 'template';
            fprintf('プリセット指定なし - テンプレート設定を使用\n');
        else
            presetName = p.Results.preset;
            fprintf('指定プリセット: %s\n', presetName);
        end

        % プリセットの完全パスを構築
        currentDir = fileparts(mfilename('fullpath'));
        presetFile = fullfile(currentDir, 'presets', [presetName '.m']);

        % プリセットファイルの存在確認
        if ~exist(presetFile, 'file')
            error('プリセットファイルが見つかりません: %s', presetFile);
        end

        % プリセットファイルを読み込んで実行
        [presetDir, presetFuncName] = fileparts(presetFile);
        addpath(presetDir);
        params = feval(presetFuncName);
        rmpath(presetDir);

        % デバイス設定を追加
        params.device = getDeviceConfig(deviceType);

        % プリセット情報の表示
        if isfield(params, 'info')
            fprintf('\nプリセット情報:\n');
            fprintf('  名前: %s\n', params.info.name);
            fprintf('  説明: %s\n', params.info.description);
            fprintf('  バージョン: %s\n', params.info.version);
            fprintf('  作成者: %s\n', params.info.author);
            fprintf('  作成日: %s\n', params.info.date);
            fprintf('---------------------------\n');
        end

        if isfield(params, 'device')
            fprintf('デバイスタイプ: %s\n', deviceType);
            fprintf('  設定チャンネル数: %d\n', params.device.channelCount);
            if isfield(params.device, 'channels') && ~isempty(params.device.channels)
                % セル配列の場合は strjoin で連結
                if iscell(params.device.channels)
                    channelList = strjoin(params.device.channels, ', ');
                else
                    channelList = num2str(params.device.channels);
                end
                fprintf('  チャンネル配置: %s\n', channelList);
            else
                fprintf('  チャンネル配置: 未定義\n');
            end
            fprintf('  サンプルレート: %d Hz\n', params.device.sampleRate);
        end

        % 設定の整合性チェック
        validateConfig(params, deviceType);
        fprintf('=== 設定読み込み完了 ===\n');

    catch ME
        % エラー情報の詳細表示
        fprintf('\n=== エラー発生 ===\n');
        fprintf('エラーメッセージ: %s\n', ME.message);
        fprintf('エラー位置:\n');
        for i = 1:length(ME.stack)
            fprintf('  File: %s\n  Line: %d\n  Function: %s\n\n', ...
                ME.stack(i).file, ME.stack(i).line, ME.stack(i).name);
        end
        rethrow(ME);
    end
end

function deviceConfig = getDeviceConfig(deviceType)
    % デバイスの基本設定を定義する関数
    switch lower(deviceType)
        case 'epocx'
            deviceConfig = struct(...
                'name', 'EPOCX', ...
                'channelCount', 14, ...
                'channelNum', [4:17], ...
                'channels', {{'AF3','F7','F3','FC5','T7','P7','O1','O2','P8','T8','FC6','F4','F8','AF4'}}, ...
                'sampleRate', 256, ...
                'resolution', 14, ...
                'reference', 'CMS/DRL', ...
                'lsl', struct(...
                    'streamName', 'EmotivDataStream-EEG', ...
                    'type', 'EEG', ...
                    'format', 'float32', ...
                    'nominal_srate', 256, ...
                    'source_id', 'emotiv_epocx_1' ...
                ), ...
                'eog', struct(...
                    'channelCount', 2, ...
                    'pairs', struct(...
                        'primary', struct(...
                            'left', 1, ...
                            'right', 14 ...
                        ), ...
                        'secondary', struct(...
                            'left', 2, ...
                            'right', 13 ...
                        ) ...
                    ) ...
                ) ...
            );
        
        case 'epocflex'
            deviceConfig = struct(...
                'name', 'EPOCFLEX', ...
                'channelCount', 32, ...     % 最大32チャンネルに対応
                'channelNum', [4:35], ...     % 1から32までのチャンネル番号
                'channels', {{'Cz','Fz','Fp1','F7','F3','FC1','C3','FC5','FT9','T7','CP5','CP1','P3','P7','PO9','O1','Pz','Oz','O2','PO10','P8','P4','CP2','CP6','T8','FT10','FC6','C4','FC2','F4','F8','Fp2'}}, ... % 10-20システムに基づく配置
                'sampleRate', 256, ...      % 256Hzのサンプリングレート
                'resolution', 16, ...       % 16ビットの解像度
                'reference', 'CMS/DRL', ... % 共通モードセンス（CMS）と駆動右脚（DRL）を参照
                'lsl', struct(...
                    'streamName', 'EmotivDataStream-EEG', ...
                    'type', 'EEG', ...
                    'format', 'float32', ...
                    'nominal_srate', 256, ...
                    'source_id', 'emotiv_epocflex' ...
                ), ...
                'eog', struct(...
                    'channelCount', 2, ...
                    'pairs', struct(...
                        'primary', struct(...
                            'left', 3, ...
                            'right', 14 ...
                        ), ...
                        'secondary', struct(...
                            'left', 32, ...
                            'right', 13 ...
                        ) ...
                    ) ...
                ) ...
            );

        case 'mn8'
            deviceConfig = struct(...
                'name', 'MN8', ...
                'channelNum', [4:5], ...
                'channelCount', 2, ...
                'channels', {{'T7','T8'}}, ...
                'sampleRate', 128, ...
                'resolution', 8, ...
                'reference', 'CMS/DRL', ...
                'lsl', struct(...
                    'streamName', 'EmotivDataStream-EEG', ...
                    'type', 'EEG', ...
                    'format', 'float32', ...
                    'nominal_srate', 128, ...
                    'source_id', 'emotiv_mn8' ...
                ) ...
            );

        case 'openbci8'
            deviceConfig = struct(...
                'name', 'OPENBCI8', ...
                'channelNum', [1:8], ...
                'channelCount', 8, ...
                'channels', {{'Fp1','Fp2','C3','C4','P7','P8','O1','O2'}}, ...
                'sampleRate', 125, ...
                'resolution', 24, ...
                'reference', 'SRB', ...
                'lsl', struct(...
                    'streamName', 'OpenBCI-EEG', ...
                    'type', 'EEG', ...
                    'format', 'float32', ...
                    'nominal_srate', 125, ...
                    'source_id', 'openbci_8ch' ...
                ) ...
            );

        case 'openbci16'
            deviceConfig = struct(...
                'name', 'OPENBCI16', ...
                'channelNum', [1:16], ...
                'channelCount', 16, ...
                'channels', {{'Fp1','Fp2','F3','F4','C3','C4','P3','P4','O1','O2','F7','F8','T7','T8','P7','P8'}}, ...
                'sampleRate', 250, ...
                'resolution', 24, ...
                'reference', 'SRB', ...
                'lsl', struct(...
                    'streamName', 'OpenBCI-EEG', ...
                    'type', 'EEG', ...
                    'format', 'float32', ...
                    'nominal_srate', 250, ...
                    'source_id', 'openbci_16ch' ...
                ) ...
            );

        case 'select'
            deviceConfig = struct(...
                'name', 'SELECT', ...
                'channelCount', 6, ...     % 最大32チャンネルに対応
                'channelNum', [1, 2, 6, 8, 27, 29], ...     % チャンネル番号
                'channels',  {{'Cz', 'Fz', 'FC1', 'FC5', 'FC6', 'FC2'}}, ...
                'sampleRate', 256, ...      % 256Hzのサンプリングレート
                'resolution', 16, ...       % 16ビットの解像度
                'reference', 'CMS/DRL' ... % 共通モードセンス（CMS）と駆動右脚（DRL）を参照
            );

        otherwise
            error('Unknown device type: %s', deviceType);
    end
end

function validateConfig(params, deviceType)
    % 設定の整合性をチェックする関数

    % 必須フィールドの確認
    requiredFields = {'device'};
    for i = 1:length(requiredFields)
        if ~isfield(params, requiredFields{i})
            error('必須フィールドが欠落しています: %s', requiredFields{i});
        end
    end

    % デバイス設定の整合性チェック
    if ~strcmpi(params.device.name, getDeviceConfig(deviceType).name)
        warning('デバイス名が一致しません。設定: %s, 期待値: %s', ...
            params.device.name, getDeviceConfig(deviceType).name);
    end

    % プリセット固有の設定が存在する場合の追加チェック
    if isfield(params, 'signal') && isfield(params.signal, 'window')
        % サンプリングレートと時間窓の検証
        if isfield(params.signal.window, 'epochDuration')
            % epochDurationの有効性をチェック - 条件を分けて評価
            if ~isnumeric(params.signal.window.epochDuration)
                warning('epochDurationが数値ではありません');
            elseif params.signal.window.epochDuration <= 0
                warning('epochDurationが正しくありません: %f', params.signal.window.epochDuration);
            end
        elseif isfield(params.signal.window, 'analysis')
            % 旧フィールド名の場合はanalysisをチェック - 条件を分けて評価
            if ~isnumeric(params.signal.window.analysis)
                warning('analysisが数値ではありません');
            elseif params.signal.window.analysis <= 0
                warning('analysisが正しくありません: %f', params.signal.window.analysis);
            end
        else
            warning('epochDurationまたはanalysisが設定されていません');
        end
        
        % timeRangeの検証
        if isfield(params.signal.window, 'timeRange')
            % timeRangeのフォーマットをチェック
            if iscell(params.signal.window.timeRange)
                % 複数時間範囲の場合
                for i = 1:length(params.signal.window.timeRange)
                    range = params.signal.window.timeRange{i};
                    if ~isnumeric(range)
                        warning('timeRange[%d]が数値ではありません', i);
                    elseif length(range) ~= 2
                        warning('timeRange[%d]のサイズが正しくありません', i);
                    elseif range(1) >= range(2)
                        warning('timeRange[%d]の値が正しくありません: [%s]', i, mat2str(range));
                    end
                end
            elseif isnumeric(params.signal.window.timeRange)
                % 単一時間範囲の場合
                if size(params.signal.window.timeRange, 2) ~= 2
                    warning('timeRangeの形式が正しくありません: %s', mat2str(params.signal.window.timeRange));
                elseif any(params.signal.window.timeRange(:,1) >= params.signal.window.timeRange(:,2))
                    warning('timeRangeの値が正しくありません: %s', mat2str(params.signal.window.timeRange));
                end
            else
                warning('timeRangeの形式が正しくありません');
            end
        else
            warning('timeRangeが設定されていません');
        end

        % チャンネル数の整合性
        if isfield(params.device, 'channels') && isfield(params.device, 'channelCount')
            if length(params.device.channels) ~= params.device.channelCount
                warning('チャンネル数の設定に不整合があります: 実際=%d, 設定=%d', ...
                    length(params.device.channels), params.device.channelCount);
            end
        end
    end
end