function preset = template_preset()
    %% === プリセット情報 ===
    preset_info = struct(...
        'name', 'template', ...
        'description', 'Default template preset', ...
        'version', '1.0', ...
        'author', 'Your Name', ...
        'date', '2025-01-01' ...
    );

    %% === トリガーマッピング設定 ===
%      % トリガーマッピングの設定
%     n = 80; % 最大値
%     trigger_mappings = cell(n, 2);
%     for i = 1:n
%         trigger_mappings(i,:) = {num2str(i), i};
%     end
% 
%     % マッピング構造体の生成（通常は変更不要）
%     mapping_struct = struct();
%     for i = 1:size(trigger_mappings, 1)
%         field_name = sprintf('trigger%d', i);
%         mapping_struct.(field_name) = struct(...
%             'text', trigger_mappings{i,1}, ...
%             'value', trigger_mappings{i,2} ...
%         );
%     end
    
    trigger_mappings = {
        '安静', 1;         % クラス1：安静状態（基準状態）
        'タスク', 2;       % クラス2：タスク状態
    };

    mapping_struct = struct();
    for i = 1:size(trigger_mappings, 1)
        field_name = sprintf('trigger%d', i);
        mapping_struct.(field_name) = struct(...
            'text', trigger_mappings{i,1}, ...
            'value', trigger_mappings{i,2} ...
        );
    end
    
    %% === LSL設定 ===
    lsl = struct(...
        'simulate', struct(...
            'enable', false, ...
            'signal', struct(...
                'alpha', struct(...
                    'freq', 10, ...
                    'amplitude', 20 ...
                ), ...
                'beta', struct(...
                    'freq', 20, ...
                    'amplitude', 10 ...
                ) ...
            ) ...
        ) ...
    );

    %% === データ収集設定 ===
    acquisition = struct(...
        'mode', 'offline', ...       % モード選択: 'offline'（解析用）または 'online'（リアルタイム処理用）
        'save', struct(...
            'enable', true, ...      % データ保存の有効/無効
            'name', 'template', ...      % 保存時のファイル名プレフィックス
            'path', './Experiment Data', ... % データ保存先ディレクトリ
            'saveInterval', 60, ...   % 一時保存を行う間隔（秒）
            'fields', struct(...      % 保存する項目の選択
                'params', true, ...             % 設定情報
                'rawData', true, ...            % 生脳波データ
                'labels', true, ...             % イベントマーカー
                'processedData', true, ...      % 前処理済みデータ
                'processedLabel', true, ...     % 処理済みラベル
                'processingInfo', true, ...     % 処理情報
                'classifier', true, ...      % SVM分類器
                'results', true ...             % 解析結果
            ) ...
        ), ...
        'load', struct(...           % データ読み込み設定
            'enable', true, ...      % データ読み込みの有効/無効
            'filename', '', ...       % 読み込むファイル名（フォルダから選択して読み込み）
            'path', '', ...          % 読み込むファイルのパス（フォルダから選択して読み込み）
            'fields', struct(...      % 保存する項目の選択
                'params', true, ...             % 設定情報
                'rawData', true, ...            % 生脳波データ
                'labels', true, ...             % イベントマーカー
                'processedData', true, ...      % 前処理済みデータ
                'processedLabel', true, ...     % 処理済みラベル
                'processingInfo', true, ...     % 処理情報
                'classifier', true, ...      % SVM分類器
                'results', true ...             % 解析結果
            ) ...
        ) ...
    );

    %% === 通信設定 ===
    udp = struct(...
        'receive', struct(...
            'enable', true, ...         % UDP受信の有効/無効
            'port', 12345, ...          % 受信ポート番号
            'address', '127.0.0.1', ... % 受信アドレス
            'bufferSize', 1024, ...     % 受信バッファサイズ
            'encoding', 'UTF-8', ...    % 文字エンコーディング
            'triggers', struct(...       % トリガー設定
                'enabled', true, ...     % トリガー処理の有効/無効
                'mappings', mapping_struct, ... % トリガーマッピング
                'defaultValue', 0 ...    % デフォルト値
            ) ...
        ), ...
        'send', struct(...
            'enabled', true, ...        % UDP送信の有効/無効
            'port', 54321, ...          % 送信ポート番号
            'address', '127.0.0.1', ... % 送信先アドレス
            'bufferSize', 1024, ...     % 送信バッファサイズ
            'encoding', 'UTF-8' ...     % 文字エンコーディング
        ) ...
    );

    %% === 信号処理設定 ===
    signal = struct(...
        'enable', true, ...           % 信号処理の有効/無効
        'window', struct(...           % 解析窓の設定
            'analysis', 2.0, ...       % 解析窓の長さ（秒）
            'stimulus', 5.0, ...       % 刺激提示時間（秒）
            'bufferSize', 15, ...      % データバッファのサイズ（秒）
            'updateBuffer', 1, ...     % バッファの更新間隔（秒）
            'step', [], ...            % 解析窓のシフト幅：自動計算
            'updateInterval', [] ...    % 更新間隔：自動計算
        ), ...
        'epoch', struct(...            
            'method', 'time', ...      
            'storageType', 'array', ... 
            'overlap', 0.25, ...
            'baseline', [-0.5 0], ...
            'visual', struct(...       % 視覚タスク関連の設定を追加
                'enable', false, ...   % 視覚タスクの有効/無効
                'taskTypes', {'observation', 'imagery'}, ... % タスクタイプ
                'observationDuration', 5.0, ... % 観察タスク時間(s)
                'signalDuration', 1.0, ...      % 合図時間(s) 
                'imageryDuration', 5.0 ...      % イメージタスク時間(s)
            ) ...
        ), ...
        'frequency', struct(...         % 周波数解析の設定
            'min', 1, ...              % 解析する最小周波数（Hz）
            'max', 50, ...             % 解析する最大周波数（Hz）
            'bands', struct(...         % 周波数帯域の定義
                'delta', [1 4], ...    % デルタ波帯域（Hz）
                'theta', [4 8], ...    % シータ波帯域（Hz）
                'alpha', [8 13], ...   % アルファ波帯域（Hz）
                'beta',  [13 30], ...  % ベータ波帯域（Hz）
                'gamma', [30 50] ...   % ガンマ波帯域（Hz）
            ) ...
        ), ...
        'preprocessing', struct(...    % 前処理設定
            'artifact', struct(...     % アーティファクト除去設定
                'enable', false, ...
                'method', 'all', ...   % 'all', 'eog', 'emg', 'baseline', 'threshold'
                'thresholds', struct(...
                    'eog', 100, ...    % 眼球運動の閾値(μV)
                    'emg', 100, ...    % 筋電の閾値(μV)
                    'amplitude', 150 ... % 振幅の閾値(μV)
                ), ...
                'windowSize', 1.0 ...   % 解析窓サイズ(秒)
            ), ...
            'baseline', struct(...      % ベースライン補正設定
                'enable', false, ...
                'method', 'interval', ... % 'interval', 'trend', 'dc', 'moving'
                'windowSize', 1.0, ...    % 窓サイズ(秒)
                'overlap', 0.5 ...        % オーバーラップ率
            ), ...
            'downsample', struct(...    % ダウンサンプリング設定
                'enable', false, ...
                'targetRate', 128, ...   % 目標サンプリングレート(Hz)
                'filterOrder', 30 ...    % フィルタ次数
            ), ...
            'filter', struct(...        % フィルタリング設定
                'notch', struct(...     % ノッチフィルタ
                    'enable', false, ...
                    'frequency', [50 60], ... % 除去する周波数
                    'bandwidth', 2 ...    % フィルタの帯域幅（Hz）
                ), ...
                'fir', struct(...       % FIRフィルタ
                    'enable', true, ...
                    'scaledPassband', true, ... % パスバンドのスケーリング
                    'filterOrder', 1024, ...
                    'designMethod', 'window', ...
                    'windowType', 'hamming', ...
                    'passbandRipple', 1, ...
                    'stopbandAttenuation', 60 ...
                ) ...
            ), ...
            'normalize', struct(...     % 正規化設定
                'enable', true, ...     % 正規化の有効/無効
                'type', 'all', ...       % 正規化の種類：'all'または'epoch'
                'method', 'robust' ...   % 正規化方法：'zscore', 'minmax', 'robust'
            ), ...
            'augmentation', struct(... % データ拡張設定
                'enable', false, ...    % データ拡張の有効/無効
                'augmentationRatio', 4, ... % 元のデータに対する拡張データの比率
                'combinationLimit', 3, ... % 1回の拡張で適用できる最大手法数
                'methods', struct(...   % 拡張手法の設定
                    'noise', struct(...  % ノイズ付加
                        'enable', true, ...
                        'types', {{'gaussian', 'pink'}}, ...
                        'variance', 0.01, ...
                        'probability', 0.5 ...
                    ), ...
                    'scaling', struct(... % スケーリング
                        'enable', false, ...
                        'range', [0.9 1.1], ...
                        'probability', 0.3 ...
                    ), ...
                    'timeshift', struct(... % 時間シフト
                        'enable', false, ...
                        'maxShift', 0.1, ... % 最大シフト量（秒）
                        'probability', 0.3 ...
                    ), ...
                    'mirror', struct(...    % 反転
                        'enable', false, ...
                        'probability', 0.2 ...
                    ), ...
                    'channelSwap', struct(... % チャンネル入れ替え
                        'enable', false, ...
                        'pairs', {{{'F3','F4'}, {'C3','C4'}, {'P3','P4'}}}, ...
                        'probability', 0.2 ...
                    ) ...
                ) ...
            ) ...
        ) ...
    );

    %% === 特徴抽出設定 ===
    feature = struct(...
        'power', struct(...            % パワー特徴抽出の設定
            'enable', true, ...        % パワー解析の有効/無効
            'method', 'welch', ...     % パワー計算方法: 'welch' または 'filter'
                'normalize', struct(...
                'enable', true, ...    % 正規化の有効/無効
                'methods', {{'relative', 'log'}} ... % 正規化方法: 'relative', 'log', 'zscore', 'db', 'robust'
            ), ...
            'welch', struct(...        % Welch法のパラメータ設定
                'windowType', 'hamming', ... % 窓関数: 'hamming', 'hann', 'blackman'
                'windowLength', 256, ...     % 窓長（サンプル数）
                'overlap', 0.5, ...          % オーバーラップ率（0-1）
                'nfft', 512, ...            % FFTポイント数
                'freqResolution', 0.5, ...   % 周波数分解能（Hz）
                'segmentNum', 8 ...          % 平均化セグメント数
            ), ...
            'filter', struct(...       % フィルタリング法のパラメータ
                'type', 'butter', ...  % フィルタタイプ: 'butter'
                'order', 4 ...         % フィルタ次数（2-8推奨）
            ), ...
            'bands', struct(...         % 周波数帯域の定義
                'names', {{'delta', 'theta', 'alpha', 'beta', 'gamma'}}, ...
                'delta', [0.5 4], ...   % デルタ波帯域（Hz）
                'theta', [4 8], ...     % シータ波帯域（Hz）
                'alpha', [8 13], ...    % アルファ波帯域（Hz）
                'beta',  [13 30], ...   % ベータ波帯域（Hz）
                'gamma', [30 45] ...    % ガンマ波帯域（Hz）
            ) ...
        ), ...
        'faa', struct(...              % FAAExtractor用の設定
            'enable', true, ...
            'channels', struct(...
                'left', [1, 3], ...    % 左前頭葉チャンネル（EPOC Xの場合）
                'right', [14, 12] ...  % 右前頭葉チャンネル（EPOC Xの場合）
            ), ...
            'threshold', 0.5 ...       % FAA判定の閾値
        ), ...
        'abRatio', struct(...          % ABRatioExtractor用の設定
            'enable', true, ...
            'channels', struct(...
                'left', [1, 3], ...    % 左前頭葉チャンネル（EPOC Xの場合）
                'right', [14, 12] ...  % 右前頭葉チャンネル（EPOC Xの場合）
            ), ...
            'threshold', 1.0 ...       % α/β比の閾値
        ), ...
        'emotion', struct(...          % EmotionExtractor用の設定
            'enable', true, ...
            'channels', struct(...
                'left', [1, 3], ...    % 左前頭葉チャンネル（EPOC Xの場合）
                'right', [14, 12] ...  % 右前頭葉チャンネル（EPOC Xの場合）
            ), ...
            'threshold', 0.3, ...      % 中心領域の判定閾値
            'labels', struct(...
                'states', {{'興奮', '喜び', '快適', 'リラックス', ...
                           '眠気', '憂鬱', '不快', '緊張', '安静'}}, ...
                'neutral', '安静' ...
            ), ...
            'coordinates', struct(...   % 座標変換設定
                'normalizeMethod', 'tanh', ...
                'scaling', 1.0 ...
            ) ...
        ), ...
        'csp', struct(...              % CSPExtractor用の設定
            'enable', true, ...
            'patterns', 3, ...          % 使用するパターン数
            'regularization', 0.05 ...  % 正則化パラメータ
        ) ...
    );

    %% === 分類器設定 ===
    num_classes = size(trigger_mappings, 1);        % クラス数を動的に設定
    
    classifier = struct(...
        'activeClassifier', 'cnn', ...  % アクティブな分類器タイプ: 'svm', 'ecoc', 'cnn'
        'svm', struct(...    % SVMの設定
            'enable', false, ...
            'optimize', false, ...
            'probability', true, ...
            'kernel', 'linear', ...  % カーネル関数: 'linear', 'rbf', 'polynomial'
            'threshold', struct(...   % 閾値関連の設定
                'rest', 0.5, ...      % デフォルトの安静状態閾値
                'useOptimal', true, ... % 最適閾値を使用するか
                'optimal', [], ...      % 最適閾値（自動設定）
                'range', [0.1:0.05:0.9] ... % 閾値探索の範囲
            ), ...
            'hyperparameters', struct(... % ハイパーパラメータ設定
                'optimizer', 'gridsearch', ...
                'boxConstraint', [0.1, 1, 10, 100], ...
                'kernelScale', [0.1, 1, 10, 100] ...
            ) ...
        ), ...
        'ecoc', struct(...   % ECOCの設定
            'enable', true, ...
            'optimize', false, ...
            'probability', true, ...
            'kernel', 'linear', ...  % カーネル関数: 'linear', 'rbf', 'polynomial'
            'coding', 'onevsall', ... % コーディング方式: 'onevsall', 'allpairs'
            'learners', 'svm', ...    % 基本学習器: 'svm', 'tree'
            'hyperparameters', struct(... % ハイパーパラメータ設定
                'optimizer', 'gridsearch', ...
                'boxConstraint', [0.1, 1, 10, 100], ...
                'kernelScale', [0.1, 1, 10, 100] ...
            ) ...
        ), ...
        'cnn', struct(...    
            'enable', true, ...
            'architecture', struct(...
                'numClasses', num_classes, ...
                'convLayers', struct(...     
                    'conv1', struct('size', [3 3], 'filters', 16, 'stride', 1, 'padding', 'same'), ...
                    'conv2', struct('size', [3 3], 'filters', 32, 'stride', 1, 'padding', 'same'), ...
                    'conv3', struct('size', [3 3], 'filters', 64, 'stride', 1, 'padding', 'same') ...
                ), ...
                'poolLayers', struct(...
                    'pool1', struct('size', 2, 'stride', 2), ...
                    'pool2', struct('size', 2, 'stride', 2), ...
                    'pool3', struct('size', 2, 'stride', 2) ...
                ), ...
                'dropoutLayers', struct(...
                    'dropout1', 0.3, ...
                    'dropout2', 0.4, ...
                    'dropout3', 0.5 ...
                ), ...
                'batchNorm', true, ...
                'fullyConnected', [128 64] ...  % 全結合層のユニット数
            ), ...
            'training', struct(...
                'optimizer', struct(...
                    'type', 'adam', ...          % 最適化アルゴリズム
                    'learningRate', 0.001, ...   % 学習率を修正
                    'beta1', 0.9, ...            % Adamのβ1パラメータ
                    'beta2', 0.999, ...          % Adamのβ2パラメータ
                    'epsilon', 1e-8 ...          % 数値安定性のための小さな値
                ), ...
                'maxEpochs', 200, ...           % 最大エポック数
                'miniBatchSize', 64, ...        % ミニバッチサイズ
                'shuffle', 'every-epoch', ...   % データのシャッフル方法
                'validation', struct(...
                    'enable', false, ...
                    'frequency', 30, ...         % 検証頻度（エポックごと）
                    'patience', 20, ...          % Early Stopping待機回数
                    'holdout', 0.2 ...          % テストデータの割合
                ) ...
            ) ...
        ), ...
        'evaluation', struct(...        % 評価設定
            'enable', true, ...         % 評価機能の有効/無効
            'method', 'kfold', ...      % 評価方法
            'kfold', 5, ...             % 分割数
            'holdoutRatio', 0.2, ...    % ホールドアウト比率
            'metrics', struct(...        % 評価指標の設定
                'accuracy', true, ...    % 正解率
                'precision', true, ...   % 適合率
                'recall', true, ...      % 再現率
                'f1score', true, ...    % F1スコア
                'auc', true, ...        % AUC
                'confusion', true ...    % 混同行列
            ), ...
            'visualization', struct(...   % 可視化設定
                'enable', true, ...      % 可視化機能の有効/無効
                'confusionMatrix', true, ... % 混同行列の表示
                'roc', true, ...            % ROC曲線の表示
                'learningCurve', true, ...  % 学習曲線の表示
                'featureImportance', true ... % 特徴量重要度の表示
            ) ...
        ) ...
    );

    %% === GUI表示設定 ===
    gui = struct(...
        'display', struct(...
            'visualization', struct(...
                'refreshRate', 0.2, ...     % 表示更新レート（秒）
                'enable', struct(...        % 表示項目の有効/無効設定
                    'rawData', true, ...    % 生データの表示
                    'processedData', true, ... % 処理済みデータの表示
                    'spectrum', true, ...   % スペクトル表示
                    'ersp', true ...        % 事象関連スペクトル表示
                ), ...
                'scale', struct(...         % 表示スケールの設定
                    'auto', true, ...       % 自動スケーリング
                    'raw', [4200 4400], ... % 生データの表示範囲（μV）
                    'processed', [-40 40], ... % 処理済みデータの表示範囲（μV）
                    'freq', [0 50], ...     % 周波数表示範囲（Hz）
                    'power', [0.01 100], ... % パワー表示範囲（μV²/Hz）
                    'displaySeconds', 5 ... % 時系列データの表示時間幅（秒）
                ), ...
                'showBands', true, ...      % 周波数帯域の表示
                'ersp', struct(...          % ERSP表示の詳細設定
                    'scale', [-25 25], ...  % ERSPの表示範囲（dB）
                    'time', [0 5], ...     % 時間範囲（秒）
                    'baseline', [-1 0], ... % ベースライン期間（秒）
                    'freqRange', [1 50], ... % 周波数範囲（Hz）
                    'numFreqs', 50, ...     % 周波数分割数
                    'method', 'wavelet', ... % 解析手法
                    'colormap', struct(...   % カラーマップ設定
                        'type', 'jet', ...   % タイプ
                        'reverse', false, ... % カラーマップの反転
                        'limit', 'sym', ...  % 制限方法
                        'background', 'white' ... % 背景色
                    ) ...
                ) ...
            ) ... 
        ), ...
        'slider', struct(...              % スライダー設定
            'enable', false, ...          % スライダーの有効/無効
            'position', [800 400 400 200], ... % 位置とサイズ
            'defaultValue', 1, ...        % デフォルト値
            'minValue', 1, ...            % 最小値
            'maxValue', 9, ...            % 最大値
            'steps', 9, ...               % ステップ数
            'title', 'Label Slider' ...   % ウィンドウタイトル
        ) ...
    );

%% === デバイス設定 ===
    device = struct(...
        'epocx', struct(...
            'name', 'EPOCX', ...
            'channelCount', 14, ...
            'channelNum', (4:17), ...
            'channels', {{'AF3','F7','F3','FC5','T7','P7','O1','O2','P8','T8','FC6','F4','F8','AF4'}}, ...
            'sampleRate', 256, ...
            'resolution', 14, ...
            'reference', 'CMS/DRL', ...
            'lsl', struct(...
                'streamName', 'EmotivDataStream-EEG', ...
                'type', 'EEG', ...
                'format', 'float32', ...
                'nominal_srate', 256, ...
                'source_id', 'emotiv_epocx_1' ...
            ) ...
        ), ...
        'epocx128', struct(...
            'name', 'EPOCX', ...
            'channelCount', 14, ...
            'channelNum', (4:17), ...
            'channels', {{'AF3','F7','F3','FC5','T7','P7','O1','O2','P8','T8','FC6','F4','F8','AF4'}}, ...
            'sampleRate', 128, ...
            'resolution', 14, ...
            'reference', 'CMS/DRL', ...
            'lsl', struct(...
                'streamName', 'EmotivDataStream-EEG', ...
                'type', 'EEG', ...
                'format', 'float32', ...
                'nominal_srate', 256, ...
                'source_id', 'emotiv_epocx_1' ...
            ) ...
        ), ...
        'mn8', struct(...
            'name', 'MN8', ...
            'channelNum', (4:5), ...
            'channelCount', 2, ...
            'channels', {{'T7','T8'}}, ...
            'sampleRate', 128, ...
            'resolution', 8, ...
            'reference', 'CMS/DRL', ...
            'lsl', struct(...
                'streamName', 'EmotivDataStream-EEG', ...
                'type', 'EEG', ...
                'format', 'float32', ...
                'nominal_srate', 128, ...
                'source_id', 'emotiv_mn8_1' ...
            ) ...
        ), ...
        'openbci8', struct(...
            'name', 'OPENBCI8', ...
            'channelNum', (1:8), ...
            'channelCount', 8, ...
            'channels', {{'Fp1','Fp2','C3','C4','P7','P8','O1','O2'}}, ...
            'sampleRate', 125, ...
            'resolution', 24, ...
            'reference', 'SRB', ...
            'lsl', struct(...
                'streamName', 'OpenBCI-EEG', ...
                'type', 'EEG', ...
                'format', 'float32', ...
                'nominal_srate', 125, ...
                'source_id', 'openbci_8ch_1' ...
            ) ...
        ), ...
        'openbci16', struct(...
            'name', 'OPENBCI16', ...
            'channelNum', (1:16), ...
            'channelCount', 16, ...
            'channels', {{'Fp1','Fp2','F3','F4','C3','C4','P3','P4','O1','O2','F7','F8','T7','T8','P7','P8'}}, ...
            'sampleRate', 250, ...
            'resolution', 24, ...
            'reference', 'SRB', ...
            'lsl', struct(...
                'streamName', 'OpenBCI-EEG', ...
                'type', 'EEG', ...
                'format', 'float32', ...
                'nominal_srate', 250, ...
                'source_id', 'openbci_16ch_1' ...
            ) ...
        ) ...
    );

    %% === プリセット構造体の構築 ===
    preset = struct();
    preset.info = preset_info;
    preset.device = device;
    preset.acquisition = acquisition;
    preset.lsl = lsl;
    preset.udp = udp;
    preset.signal = signal;
    preset.feature = feature;
    preset.classifier = classifier;
    preset.gui = gui;
end